#!/usr/bin/env lua

Yaml = require('yaml')

function GetOutputOfShellCommand(command)
  local handle = assert(io.popen(command))
  local ret = assert(handle:read("a"))
  assert(handle:close())
  ret = string.gsub(ret, '^%s+', '')
  ret = string.gsub(ret, '%s+$', '')
  ret = string.gsub(ret, '[\n\r]+', ' ')
  return ret
end

function RunShellCommand(command)
  return os.execute(command)
end

function CheckIfRoot()
  return assert(GetOutputOfShellCommand("id -u")) == "0"
end

function MustNotBeRoot(f)
  return function(...)
    assert(not CheckIfRoot(), "DONT RUN THIS AS ROOT!!!")
    return f(...)
  end
end

function GetConfig(path)
  local handle = assert(io.open(path))
  local text = assert(handle:read("a"))
  assert(handle:close())
  return Yaml.eval(text)
end

function CreateImage(name, path_to_dockerfile)
  local command = "docker build -t " .. name .. " " .. path_to_dockerfile
  local _ = assert(RunShellCommand(command))
end

function RunContainer(name, local_dir_path, host_port, docker_port)
  local command = "docker run -d --mount type=bind,source=" ..
                  local_dir_path .. ",target=/home/tarelka/workspace" ..
                  " --cap-add sys_ptrace -p" .. host_port .. ":" .. docker_port ..
                  " --name " .. name .. " " .. name
  local _ = assert(RunShellCommand(command))
end

function StopContainer(name)
  local command = "docker stop " .. name .. " && docker rm $_"
  local _ = assert(RunShellCommand(command))
end

function InstallPackages(name, packages)
  local command = "docker exec -it " .. name ..
                  " pacman -Syyu " .. table.concat(packages, " ")
  local _ = assert(RunShellCommand(command))
end

function LoginToContainer(name, shell)
  local command = "docker exec -it " .. name .. " " .. shell
  local _ = assert(RunShellCommand(command))
end

function HandleBuild(args, config)
  local path_to_dockerfile = assert(args[1], "You have to provide path to Dockerfile")
  local container_name = assert(config["container-name"], "Must be specified in config")
  return CreateImage(container_name, path_to_dockerfile)
end

function HandleStart(_, config)
  local host_port = assert(config["host-port"], "Must be specified in config")
  local docker_port = assert(config["docker-port"], "Must be specified in config")
  local local_dir_path = assert(config["local-dir-path"], "Must be specified in config")
  local container_name = assert(config["container-name"], "Must be specified in config")
  return RunContainer(container_name, local_dir_path, host_port, docker_port)
end

function HandleStop(_, config)
  local container_name = assert(config["container-name"], "Must be specified in config")
  return StopContainer(container_name)
end

function HandleInstall(args, config)
  local container_name = assert(config["container-name"], "Must be specified in config")
  local packages = args
  return InstallPackages(container_name, packages)
end

function HandleLogin(_, config)
  local container_name = assert(config["container-name"], "Must be specified in config")
  local shell = assert(config["shell"], "Must be specified in config")
  return LoginToContainer(container_name, shell)
end

COMMANDS =
{
  BUILD = HandleBuild,
  START = HandleStart,
  STOP = HandleStop,
  LOGIN = HandleLogin,
  INSTALL = HandleInstall
}

COMMANDS_MAP =
{
  build = COMMANDS.BUILD,
  start = COMMANDS.START,
  stop = COMMANDS.STOP,
  login = COMMANDS.LOGIN,
  install = COMMANDS.INSTALL
}

function GetCommand(command)
  return assert(COMMANDS_MAP[command], "Command " .. command " not found")
end

function GetCommandArguments(args)
  local ret = {table.unpack(args, 2)}
  return ret
end

function Main()
  local HOME = os.getenv("HOME")
  local config_path = HOME.."/.config/tarelka/tarelka.yaml"
  local config = GetConfig(config_path)

  local command = arg[1]
  local handler = COMMANDS_MAP[command]

  local args = GetCommandArguments(arg)

  handler(args, config)
end

Main = MustNotBeRoot(Main)

Main()
